#!/bin/sh

###############
# This is an old version
# A better version is available here: https://gist.github.com/AmirKarimi/ee2ea6818a4df51ce478
###############

APP_NAME="%APP_NAME%"
APP_ARGS=""

APP_BASE_PATH="/var/webapps"
APP_PATH="$APP_BASE_PATH/$APP_NAME"
EXEC_PATH="$APP_PATH/bin/$APP_NAME"
LOG_FILE="$APP_PATH/init.d.log"
PIDFILE="$APP_PATH/RUNNING_PID"

. /lib/lsb/init-functions

start() {
    echo "Starting '$APP_NAME' server..."
    $EXEC_PATH $APP_ARGS > $LOG_FILE &
}

stop() {
    echo "Shutting down '$APP_NAME' server..."
    kill `cat $PIDFILE`
}

case "$1" in
    start)
        start
	;;
    stop)
        stop
	;;
    restart)
        stop
        start
	;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
